"""Python code generation for Manas-Sutra v0.1."""

from __future__ import annotations

import re
from textwrap import indent

from .parser import ManasProgram


GENERATED_HEADER = '''"""Generated by Manas-Sutra v0.1.

Goal: {goal}
This module is an execution artifact produced from an intent specification.
Review constraints and verification requirements before production use.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


SPEC = {metadata!r}
GENERATOR_KIND = {generator_kind!r}


@dataclass(frozen=True)
class ExecutionResult:
    goal: str
    outputs: dict[str, Any]
    verification_required: tuple[str, ...]
    notes: tuple[str, ...]


INPUTS = {input_fields}
CONSTRAINTS = {constraint_lines}
VERIFICATION = {verification_lines}
OUTPUTS = {output_fields}


'''


def generate_python(program: ManasProgram) -> str:
    """Generate a Python module from a Manas-Sutra program.

    v0.1 contains a small deterministic generator registry. Known patterns can
    produce real executable behavior, while unknown goals still produce a safe
    scaffold that preserves intent, constraints, and verification metadata.
    """

    function_name = _to_snake_case(program.goal)
    body, generator_kind = _select_execution_body(program, function_name)
    metadata = program.to_dict()

    header = GENERATED_HEADER.format(
        goal=program.goal,
        metadata=metadata,
        generator_kind=generator_kind,
        input_fields=_format_tuple(program.inputs),
        constraint_lines=_format_tuple(program.constraints),
        verification_lines=_format_tuple(program.verification),
        output_fields=_format_tuple(program.outputs),
    )

    return header + body + _describe_spec_function()


def _select_execution_body(program: ManasProgram, function_name: str) -> tuple[str, str]:
    if _looks_like_sum_goal(program):
        return _sum_numbers_body(program, function_name), "sum_numbers"
    return _generic_scaffold_body(program, function_name), "generic_scaffold"


def _looks_like_sum_goal(program: ManasProgram) -> bool:
    goal = _compact(program.goal)
    inputs = {_compact(item) for item in program.inputs}
    outputs = {_compact(item) for item in program.outputs}
    has_number_input = bool(inputs & {"numbers", "numberlist", "listofnumbers"})
    has_total_output = bool(outputs & {"total", "sum", "result"})
    return "sum" in goal and has_number_input and has_total_output


def _sum_numbers_body(program: ManasProgram, function_name: str) -> str:
    number_input = _first_matching(
        program.inputs, {"numbers", "numberlist", "listofnumbers"}, fallback=program.inputs[0]
    )
    total_output = _first_matching(
        program.outputs, {"total", "sum", "result"}, fallback=program.outputs[0]
    )

    return f'''def {function_name}(**inputs: Any) -> ExecutionResult:
    """Execute the `{program.goal}` goal by summing a numeric sequence."""

    missing = [name for name in INPUTS if name not in inputs]
    if missing:
        raise ValueError(f"Missing required inputs: {{', '.join(missing)}}")

    numbers = inputs[{number_input!r}]
    if not isinstance(numbers, (list, tuple)):
        raise TypeError({number_input!r} + " must be a list or tuple of numbers")
    if not all(isinstance(value, (int, float)) for value in numbers):
        raise TypeError({number_input!r} + " must contain only int or float values")

    outputs = {{name: None for name in OUTPUTS}}
    outputs[{total_output!r}] = sum(numbers)
    notes = (
        "Executed with the built-in deterministic sum_numbers generator.",
        "Verification requirements remain attached for downstream review.",
    )
    return ExecutionResult(
        goal=SPEC["goal"],
        outputs=outputs,
        verification_required=VERIFICATION,
        notes=notes,
    )


'''


def _generic_scaffold_body(program: ManasProgram, function_name: str) -> str:
    return f'''def {function_name}(**inputs: Any) -> ExecutionResult:
    """Execute the generated scaffold for the `{program.goal}` goal."""

    missing = [name for name in INPUTS if name not in inputs]
    if missing:
        raise ValueError(f"Missing required inputs: {{', '.join(missing)}}")

    notes = (
        "Generated scaffold only; no domain generator matched this goal yet.",
        "All listed constraints must be reviewed before deployment.",
    )
    outputs = {{name: None for name in OUTPUTS}}
    return ExecutionResult(
        goal=SPEC["goal"],
        outputs=outputs,
        verification_required=VERIFICATION,
        notes=notes,
    )


'''


def _describe_spec_function() -> str:
    return '''def describe_spec() -> str:
    """Return a readable summary of the embedded Manas-Sutra specification."""

    lines = [f"Goal: {SPEC['goal']}", f"Generator: {GENERATOR_KIND}"]
    for section in ("inputs", "constraints", "verification", "outputs"):
        values = SPEC[section]
        if values:
            lines.append(f"{section.title()}:")
            lines.extend(f"  - {value}" for value in values)
    return "\\n".join(lines)
'''


def _to_snake_case(value: str) -> str:
    words = re.findall(r"[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)|\d+", value.replace("-", "_"))
    if not words:
        return "execute_goal"
    candidate = "_".join(word.lower() for word in words)
    if candidate[0].isdigit():
        candidate = f"goal_{candidate}"
    return candidate


def _format_tuple(items: tuple[str, ...]) -> str:
    if not items:
        return "()"
    rendered = "\n".join(f"{item!r}," for item in items)
    return "(\n" + indent(rendered, "    ") + "\n)"


def _compact(value: str) -> str:
    return re.sub(r"[^a-z0-9]", "", value.lower())


def _first_matching(items: tuple[str, ...], compact_names: set[str], fallback: str) -> str:
    for item in items:
        if _compact(item) in compact_names:
            return item
    return fallback
