"""Python code generation for Manas-Sutra v0.1."""

from __future__ import annotations

import re
from textwrap import indent

from .parser import ManasProgram


def generate_python(program: ManasProgram) -> str:
    """Generate a safe starter Python module from a Manas-Sutra program.

    The generator intentionally emits scaffold code plus metadata rather than
    pretending to solve every task. Later versions can plug in LLM synthesis,
    symbolic planners, or domain-specific generators behind this boundary.
    """

    function_name = _to_snake_case(program.goal)
    metadata = program.to_dict()
    constraint_lines = _format_tuple(program.constraints)
    verification_lines = _format_tuple(program.verification)
    input_fields = _format_tuple(program.inputs)
    output_fields = _format_tuple(program.outputs)

    return f'''"""Generated by Manas-Sutra v0.1.

Goal: {program.goal}
This module is a starter execution artifact. Review, complete, and verify it
before production use.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


SPEC = {metadata!r}


@dataclass(frozen=True)
class ExecutionResult:
    goal: str
    outputs: dict[str, Any]
    verification_required: tuple[str, ...]
    notes: tuple[str, ...]


INPUTS = {input_fields}
CONSTRAINTS = {constraint_lines}
VERIFICATION = {verification_lines}
OUTPUTS = {output_fields}


def {function_name}(**inputs: Any) -> ExecutionResult:
    """Execute the generated scaffold for the `{program.goal}` goal."""

    missing = [name for name in INPUTS if name not in inputs]
    if missing:
        raise ValueError(f"Missing required inputs: {{', '.join(missing)}}")

    notes = [
        "Generated scaffold only; domain implementation is intentionally explicit.",
        "All listed constraints must be reviewed before deployment.",
    ]
    outputs = {{name: None for name in OUTPUTS}}
    return ExecutionResult(
        goal=SPEC["goal"],
        outputs=outputs,
        verification_required=VERIFICATION,
        notes=tuple(notes),
    )


def describe_spec() -> str:
    """Return a readable summary of the embedded Manas-Sutra specification."""

    lines = [f"Goal: {{SPEC['goal']}}"]
    for section in ("inputs", "constraints", "verification", "outputs"):
        values = SPEC[section]
        if values:
            lines.append(f"{{section.title()}}:")
            lines.extend(f"  - {{value}}" for value in values)
    return "\\n".join(lines)
'''


def _to_snake_case(value: str) -> str:
    words = re.findall(r"[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)|\d+", value.replace("-", "_"))
    if not words:
        return "execute_goal"
    candidate = "_".join(word.lower() for word in words)
    if candidate[0].isdigit():
        candidate = f"goal_{candidate}"
    return candidate


def _format_tuple(items: tuple[str, ...]) -> str:
    if not items:
        return "()"
    rendered = "\n".join(f"{item!r}," for item in items)
    return "(\n" + indent(rendered, "    ") + "\n)"
